core/urls.py
from django.urls import path
import core.views as v

app_name = 'core'

urlpatterns = [
    path('', v.index.as_view(), name='index'),
]

estoque/urls.py
from django.urls import path, include
import estoque.views as v

app_name = 'estoque'

entrada_patterns = [
    path('', v.EstoqueEntradaList.as_view(), name='estoque_entrada_list'),
    path('add/', v.estoque_entrada_add, name='estoque_entrada_add'),
]

saida_patterns = [
    path('', v.EstoqueSaidaList.as_view(), name='estoque_saida_list'),
    path('add/', v.estoque_saida_add, name='estoque_saida_add'),
]


urlpatterns = [
    path('<int:pk>/', v.EstoqueDetail.as_view(), name='estoque_detail'),
    path('entrada/', include(entrada_patterns)),
    path('saida/', include(saida_patterns)),
]

produto/urls.py
from django.urls import path

import produto.views as v

app_name = 'produto'

urlpatterns = [
    path('', v.ProductList.as_view(), name='product_list'),
    path('<int:pk>/', v.product_detail, name='product_detail'),
    path('add/', v.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/edit', v.ProductUpdate.as_view(), name='product_edit'),
    path('<int:pk>/json/', v.product_json, name='product_json'),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('logout', LogoutView.as_view(), name='logout')
]

core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField (
        'criado em',
        auto_now_add=True,
        auto_now=False,
    )
    modified = models.DateTimeField (
        'modificado em',
        auto_now_add=False,
        auto_now=True,
    )

    class Meta:
        abstract = True

core/views.py
from django.views.generic import TemplateView


class index(TemplateView):
    template_name = 'index.html'

core/templates/includes/nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #3366ff;">
    <a class="navbar-brand" href="{% url 'core:index' %}">Estoque</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'produto:product_list' %}">Produtos</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Estoque</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="{% url 'estoque:estoque_entrada_list' %}">Entrada</a>
                    <a class="dropdown-item" href="{% url 'estoque:estoque_saida_list' %}">Saída</a>
                </div>
            </li>
        </ul>
        {% if user.is_authenticated %}
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a href="{% url 'logout' %}" class="nav-link">Sair</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>

core/templates/includes/pagination.html
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}

          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% endif %}

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?page={{ pg }}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %}
            <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?page={{ pg }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}

        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>