core/urls.py
from django.urls import path
import core.views as v

app_name = 'core'

urlpatterns = [
    path('', v.index.as_view(), name='index'),
]

produto/urls.py
from django.urls import path

import produto.views as v

app_name = 'produto'

urlpatterns = [
    path('', v.ProductList.as_view(), name='product_list'),
    path('<int:pk>/', v.product_detail, name='product_detail'),
    path('add/', v.ProductCreate.as_view(), name='product_add'),
    path('<int:pk>/edit', v.ProductUpdate.as_view(), name='product_edit'),
    path('<int:pk>/json/', v.product_json, name='product_json'),
]

projeto/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('produto/', include('produto.urls')),
    path('estoque/', include('estoque.urls')),
    path('logout', LogoutView.as_view(), name='logout')
]

produto/models.py
from django.db import models
from django.urls import reverse_lazy


class Produto(models.Model):
    produto = models.CharField('Produto', max_length=100, unique=True)
    ncm = models.CharField('NCM', max_length=8)
    preco = models.DecimalField('Preço', max_digits=8, decimal_places=2)
    estoque = models.IntegerField('Estoque atual')
    estoque_minimo = models.PositiveIntegerField('Estoque mínimo', default=0)

    class Meta:
        ordering = ('produto',)

    def __str__(self):
        return self.produto

    def get_absolute_url(self):
        return reverse_lazy('produto:product_detail', kwargs={'pk': self.pk})

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'produto': self.produto,
            'estoque': self.estoque,
        }

produto/forms.py
from django import forms
from .models import Produto


class ProdutoForm(forms.ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'

produto/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, ListView

from .forms import ProdutoForm
from .models import Produto


class ProductList(ListView):
    model = Produto
    template_name = 'product_list.html'
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        search = self.request.GET.get('search')
        if search:
            objects_list = Produto.objects.filter(produto__icontains=search)
            return objects_list

        objects_list = Produto.objects.all()
        return objects_list


def product_detail(request, pk):
    template_name = 'product_detail.html'
    obj = Produto.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


class ProductAdd(TemplateView):
    template_name = 'produto_form.html'


class ProductCreate(CreateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


class ProductUpdate(UpdateView):
    model = Produto
    template_name = 'produto_form.html'
    form_class = ProdutoForm


def product_json(request, pk):
    produto = Produto.objects.filter(pk=pk)
    data = [item.to_dict_json() for item in produto]
    return JsonResponse({'data': data})

produto/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}

<a href="{% url 'produto:product_list' %}">Voltar</a>
<h1>
    {{ object }}
    <span class="pull-right">
        <a href="{% url 'produto:product_edit' object.pk %}">
            <button type="button" class="btn btn-success">
                <span class="fa fa-pencil"></span> Editar
            </button>
        </a>
    </span>
</h1>


<div class="container bootstrap snippets bootdey">
<div class="panel-body inf-content">
    <div class="row">
        <div class="col-md-4">
            <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="https://img.freepik.com/vetores-gratis/composicao-isometrica-de-entrega-logistica-de-entrega-com-caracteres-humanos-sem-rosto-de-dois-trabalhadores-do-sexo-masculino-e-ilustracao-de-rack-de-encomendas_1284-29116.jpg?t=st=1656970619~exp=1656971219~hmac=748b924edcc98f3284db33da88aab4fc9581d021ffc0c91e038513c23ebde256&w=740" data-original-title="Usuario">
        </div>
        <div class="col-md-6">
            <strong>Detalhes</strong><br>
            <div class="table-responsive">
            <table class="table table-user-information">
                <tbody>
                    <tr>
                        <td>
                            <strong>
                                <span><i class="fa-solid fa-cart-shopping"></i></span>
                                Produto
                            </strong>
                        </td>
                        <td class="text-primary">
                            {{ object.produto }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                <span><i class="fa-solid fa-hashtag"></i></span>
                                NCM
                            </strong>
                        </td>
                        <td class="text-primary">
                            {{ object.ncm }}
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <strong>
                                <span><i class="fa-solid fa-coins"></i></span>
                                Preço
                            </strong>
                        </td>
                        <td class="text-primary">
                            R$ {{ object.preco }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <strong>
                                <span><i class="fa-solid fa-box-open"></i></span>
                                Estoque
                            </strong>
                        </td>
                        <td class="text-primary">
                            {{ object.estoque }}
                        </td>
                    </tr>

                    <tr>
                        <td>
                            <strong>
                                <span><i class="fa-solid fa-box-open"></i></span>
                                Estoque mínimo
                            </strong>
                        </td>
                        <td class="text-primary">
                            {{ object.estoque_minimo }}
                        </td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock content %}

produto/templates/product_list.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <h2>Lista de Produtos
        <span class="pull-right">
            <a href="{% url 'produto:product_add' %}">
                <button type="button" class="btn btn-primary">
                    <span class="fa fa-plus"></span> Adicionar
                </button>
            </a>
        </span>
    </h2>

<div class="row">
    <div class="col-sm-6" style="margin-top:20px;">
        <form action="." method="GET" class="form-inline">
            <input type="text" id="search" name="search" class="form-control" placeholder="Pesquisar produtos">
            <input type="submit" class="btn btn-primary" style="margin-left:5px;" value="Buscar">
        </form>
    </div>
</div>

    {% if object_list %}
    <table class="table table-striped" style="margin-top:30px;">
        <thead>
            <tr>
                <th>Produto</th>
                <th>NCM</th>
                <th>Preço</th>
                <th class="text-center">Estoque</th>
                <th class="text-center">Estoque mínimo</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>
                        <a href="{{ object.get_absolute_url }}">{{ object.produto }}</a>
                    </td>
                    <td>{{ object.ncm }}</td>
                    <td>R$ <span class="pull-right">{{ object.preco }}</span></td>
                    <td class="text-center">{{ object.estoque }}</td>
                    <td class="text-center">{{ object.estoque_minimo }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% else %}
        <p class="alert alert-warning">Lista vazia.</p>
    {% endif %}
</div>

{% include 'includes/pagination.html' %}

{% endblock content %}

produto/templates/produto_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}

<form method="POST" novalidate>
    {% csrf_token %}
    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
            <label for="{{ field.id_for_label }}">
                {% if field.field.required %}
                    <span class="required">{{ field.label }} </span>
                {% else %}
                    {{ field.label }}
                {% endif %}
            </label>
            {% render_field field class="form-control" %}
            {% for error in field.errors %}
                <span class="text-muted">{{ error }}</span>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Cadastrar</button>
</form>

{% endblock content %}